service: frontend
runtime: python27
api_version: 1
threadsafe: true
# env: flex

#xkip_files:
#- ^(?!dist)  # Skip any files not in the dist folder

handlers:
# Routing for bundles to serve directly
- url: /((?:runtime|main|polyfills|styles|vendor)\.[a-z0-9]+\.js)
  secure: always
  redirect_http_response_code: 301
  static_files: dist/reg-docs/\1
  upload: dist/reg-docs/.*

# Routing for bundle maps to serve directly
- url: /((?:runtime|main|polyfills|styles|vendor)\.[a-z0-9]+\.js\.map)
  secure: always
  redirect_http_response_code: 301
  static_files: dist/reg-docs/\1
  upload: dist/reg-docs/.*

# Routing for a prod styles.bundle.css to serve directly
- url: /(styles\.[a-z0-9]+\.css)
  secure: always
  redirect_http_response_code: 301
  static_files: dist/reg-docs/\1
  upload: dist/reg-docs/.*

# Routing for typedoc, assets, and favicon.ico to serve directly
- url: /((?:assets)/.*|favicon\.ico)
  secure: always
  redirect_http_response_code: 301
  static_files: dist/reg-docs/\1
  upload: dist/reg-docs/.*

# Routing for service worker files serve directly
- url: /(manifest\.json|ngsw\.json|ngsw-worker\.js|safety-worker\.js|worker-basic\.min\.js|ngsw_worker\.es6\.js\.map)
  secure: always
  redirect_http_response_code: 301
  static_files: dist/reg-docs/\1
  upload: dist/reg-docs/.*

# Any other requests are routed to index.html for angular to handle so we don't need hash URLs
- url: /.*
  secure: always
  redirect_http_response_code: 301
  static_files: dist/reg-docs/index.html
  upload: dist/reg-docs/index\.html
  http_headers:
    Strict-Transport-Security: max-age=31536000; includeSubDomains
    X-Frame-Options: DENY

- url: /
  static_dir: dist/reg-docs

# manual_scaling:
#     instances: 1
#  
##handlers:  
# - url: /
#   static_files: dist/reg-docs/index.html
#   upload: dist/reg-docs/index.html
#
# - url: /
#   static_dir: dist/reg-docs
#
# - url: /
#   static_files: dist/index.html
#   upload: dist/index.html
#
##- url: /(.*\.css)
##  mime_type: text/css
##  static_files: dist/reg-docs/\1
##  upload: dist/reg-docs/(.*\.css)
##
##- url: /(.*\.ico)
##  mime_type: image/x-icon
##  static_files: dist/reg-docs/\1
##  upload: dist/reg-docs/(.*\.ico)
##  expiration: "7d"
##
##- url: /(.*\.js)
##  mime_type: text/javascript
##  static_files: dist/reg-docs/\1
##  upload: dist/reg-docs/(.*\.js)
##
### index files
##- url: /(.+)/?
##  static_files: dist/reg-docs/index.html
##  upload: dist/reg-docs/index.html
##  expiration: "15m"
##
##- url: /(.+)
##  static_files: dist/reg-docs/index.html
##  upload: dist/reg-docs/index.html
##  expiration: "15m"
##
### site root
##- url: /
##  static_files: dist/reg-docs/index.html
##  upload: dist/reg-docs/index.html
##  expiration: "15m"
##  
##- url: /
##  static_dir: dist/reg-docs
  